import unittest

from hungarian_stemmer.hungarian_stemmer import HungarianStemmer


class HungarianStemmerTestCase(unittest.TestCase):
    def test_stem(self):
        hunstem = HungarianStemmer()
        word = "megcsinálták"
        self.assertEqual(hunstem.stem(word), ("megcsinál",))

    def test_analyze(self):
        hunstem = HungarianStemmer()
        word = "megcsinálták"
        self.assertEqual(
            hunstem.analyze(word),
            ("ip:PREF sp:meg  st:csinál po:vrb ts:PRES_INDIC_INDEF_SG_3 " "is:PAST_INDIC_DEF_PL_3",),
        )

    def test_suggest(self):
        hunstem = HungarianStemmer()
        word = "megcsinálták"
        self.assertEqual(
            hunstem.suggest(word),
            (
                "megcsináltak",
                "megcsinálták",
                "megcsinálték",
                "megcsináltál",
                "megcsinálnák",
                "megcsináltok",
                "megcsináltuk",
                "megcsinálják",
                "meg csinálták",
                "meg-csinálták",
            ),
        )

    def test_suffix_suggest(self):
        hunstem = HungarianStemmer()
        word = "csinál"
        print(hunstem.suffix_suggest(word))
        self.assertEqual(
            hunstem.suffix_suggest(word),
            (
                "csinálnia",
                "csinálja",
                "csinálja",
                "csinálhatnékja",
                "csinálócska",
                "csinálhatnéka",
                "csinálna",
                "csinálta",
                "csinálva",
                "csinálatlanabb",
                "csinálhatatlanabb",
                "csináltathatatlanabb",
                "csinálódósabb",
                "csináltabb",
                "csinálóbb",
                "csinálhatóbb",
                "csináltathatóbb",
                "csináltatóbb",
                "csináld",
                "csináljad",
                "csináltad",
                "csinálod",
                "csinálhatnékod",
                "csinálhatnékod",
                "csinálnod",
                "csinálnád",
                "csinálásilag",
                "csinálatlanság",
                "csinálhatatlanság",
                "csináltathatatlanság",
                "csináltság",
                "csinálandóság",
                "csinálhatóság",
                "csináltathatóság",
                "csinálatlansági",
                "csinálhatatlansági",
                "csináltathatatlansági",
                "csináltsági",
                "csinálhatósági",
                "csináltathatósági",
                "csinálni",
                "csinálási",
                "csinálódási",
                "csinálgatási",
                "csináltatási",
                "csinálatlanságnyi",
                "csinálhatatlanságnyi",
                "csináltathatatlanságnyi",
                "csináltságnyi",
                "csinálhatóságnyi",
                "csináltathatóságnyi",
                "csinálásnyi",
                "csinálódásnyi",
                "csinálgatásnyi",
                "csináltatásnyi",
                "csinálónyi",
                "csináltathatónyi",
                "csináltatónyi",
                "csinálói",
                "csináltathatói",
                "csináltatói",
                "csinálj",
                "csináljak",
                "csinállak",
                "csináljalak",
                "csináltalak",
                "csinálnálak",
                "csinálnak",
                "csináljanak",
                "csinálnának",
                "csináltak",
                "csinálatlanabbik",
                "csinálhatatlanabbik",
                "csináltathatatlanabbik",
                "csinálódósabbik",
                "csináltabbik",
                "csinálóbbik",
                "csinálhatóbbik",
                "csináltathatóbbik",
                "csináltatóbbik",
                "csinálódik",
                "csinálunk",
                "csináljunk",
                "csinálhatnékunk",
                "csinálhatnékunk",
                "csinálnunk",
                "csináltunk",
                "csinálnánk",
                "csinálnánk",
                "csinálok",
                "csinálniok",
                "csináltok",
                "csináljatok",
                "csináltatok",
                "csinálhatnékotok",
                "csinálhatnékotok",
                "csinálnotok",
                "csináljátok",
                "csináljátok",
                "csinálnátok",
                "csinálnátok",
                "csináltátok",
                "csinálniuk",
                "csináljuk",
                "csináljuk",
                "csinálhatnékjuk",
                "csinálhatnékjuk",
                "csinálhatnékuk",
                "csinálhatnékuk",
                "csináltuk",
                "csinálják",
                "csinálják",
                "csinálnák",
                "csinálták",
                "csinálnék",
                "csinálnók",
                "csináljál",
                "csinálnál",
                "csináltál",
                "csináljam",
                "csináltam",
                "csináltam",
                "csinálom",
                "csinálhatnékom",
                "csinálhatnékom",
                "csinálnom",
                "csinálnám",
                "csinálatlanabban",
                "csinálhatatlanabban",
                "csináltathatatlanabban",
                "csinálódósabban",
                "csináltabban",
                "csinálóbban",
                "csinálhatóbban",
                "csináltathatóbban",
                "csináltatóbban",
                "csinálatlan",
                "csinálhatatlan",
                "csináltathatatlan",
                "csináljon",
                "csinálván",
                "csináltságos",
                "csinálásos",
                "csinálódásos",
                "csinálgatásos",
                "csináltatásos",
                "csinálás",
                "csinálódás",
                "csinálgatás",
                "csináltatás",
                "csinálós",
                "csinálódós",
                "csinálhatós",
                "csináltathatós",
                "csináltatós",
                "csinált",
                "csinált",
                "csinálgat",
                "csinálhat",
                "csinálódhat",
                "csinálgathat",
                "csináltathat",
                "csináltat",
                "csinálódott",
                "csinálgatott",
                "csinálhatott",
                "csinálódhatott",
                "csinálgathatott",
                "csináltathatott",
                "csináltatott",
                "csináltatott",
                "csinálsz",
                "csinálná",
                "csináló",
                "csinálandó",
                "csinálódó",
                "csinálgató",
                "csinálható",
                "csinálgatható",
                "csináltatható",
                "csináltató",
                "csinálatlanságú",
                "csinálhatatlanságú",
                "csináltathatatlanságú",
                "csináltságú",
                "csinálhatóságú",
                "csináltathatóságú",
                "csinálójú",
                "csináltathatójú",
                "csináltatójú",
                "csinálású",
                "csinálódású",
                "csinálgatású",
                "csináltatású",
            ),
        )

    def test_spell(self):
        hunstem = HungarianStemmer()
        word = "megcsinálták"
        self.assertTrue(hunstem.spell(word))


if __name__ == "__main__":
    unittest.main()
